/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();
self.skipWaiting();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// SPA routing: return index.html for navigation requests
const handler = createHandlerBoundToURL('/VMS/index.html');
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/_/, /\/[^/?]+\.[^/]+$/],
});
registerRoute(navigationRoute);

// Listen for push notifications
self.addEventListener('push', (event) => {
  if (event.data) {
    try {
      const data = event.data.json();
      
      let vibrationPattern = [300, 100, 300]; // Default New Visitor
      let soundUrl = '/VMS/sounds/visitor-arrived.mp3';

      switch (data.type) {
        case 'REMINDER':
          vibrationPattern = [150, 100, 150];
          soundUrl = '/VMS/sounds/reminder.mp3';
          break;
        case 'APPROVED':
          vibrationPattern = [100];
          soundUrl = '/VMS/sounds/approval.mp3';
          break;
        case 'REJECTED':
          vibrationPattern = [200, 100, 200];
          soundUrl = '/VMS/sounds/rejected.mp3';
          break;
        case 'MEETING_COMPLETED':
          vibrationPattern = [150];
          soundUrl = '/VMS/sounds/meeting-completed.mp3';
          break;
        case 'SYSTEM':
          vibrationPattern = [100, 50, 100];
          soundUrl = '/VMS/sounds/security-alert.mp3';
          break;
      }

      const options: any = {
        body: data.body,
        icon: '/VMS/pwa-192x192.png',
        badge: '/VMS/masked-icon.svg',
        vibrate: vibrationPattern,
        sound: soundUrl,
        data: {
          url: data.url || '/VMS/',
          visitorId: data.visitorId
        }
      };
      event.waitUntil(self.registration.showNotification(data.title, options));
    } catch (e) {
      console.error('Error parsing push data', e);
    }
  }
});

// Handle notification click (Deep link to specific tab/visitor)
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const targetUrl = event.notification.data.url;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url.includes('/VMS/') && 'focus' in client) {
          client.focus();
          return client.navigate(targetUrl);
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
